kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: mentalarts
networking:
  ipFamily: dual
nodes:
- role: control-plane
  image: kindest/node:v1.26.3
  # extraPortMappings: # Use this port mappings wisely :)
  # - containerPort: 30080
  #   hostPort: 30080
  #   listenAddress: "0.0.0.0"
  #   protocol: TCP
- role: worker
  image: kindest/node:v1.26.3
- role: worker
  image: kindest/node:v1.26.3
- role: worker
  image: kindest/node:v1.26.3