apiVersion: v1
kind: Service
metadata:
  name: fastapi-demo-nodeport
spec:
  type: NodePort
  #type: ClusterIP
  selector:
    app: fastapi-demo
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 31111


